### ISSUE TITLE
website analytics?

### ISSUE THREAD

**Issue by lheagy** [geoscixyz/3dem-7#5]
I am not sure if this is worth it, but if it is straightforward to do, it might be useful to set up analytics. I am thinking primarily this could be useful to get a sense of the reach of our email blasts and to identify areas of the world that we might be missing. 

@santisoler: do you have suggestions for setting up analytics?

**Comment by santisoler** [comment]
I would recommend https://plausible.io/. This is what we use in Fatiando's website, in the BIRS Workshop website and I also use it in my personal website.

Here is the link to [the proposal](https://github.com/softwareunderground/swung-org/blob/main/proposals/01-plausible-analytics.md) that @leouieda wrote asking swung to cover the costs of Plausible for swung related projects. We could ask if it's ok to use their account for the 3dem website, or we can also pay our own service.

Since the proposal is already considering other projects besides Fatiando, like SimPEG, I think it might be better to go that route.

**Comment by lheagy** [comment]
Thanks Santi! I set up a free trial for now, here is the snippet we need: 
```
<script defer data-domain="3dem.geosci.xyz" src="https://plausible.io/js/script.js"></script>
```

Would you mind adding this to the site? I suspect that we might end up opting to pay for this service, between simpeg and geosci, we have about 10ish subdomains at this point, so I don't want to eat up swung's available slots
